const global = [
  {
    category: "groceeey",
    id: "1",
    model: "Rice",
    image:
      "https://www.bigbasket.com/media/uploads/p/xxl/40000750_2-india-gate-basmati-rice-mograbroken.jpg",
    price: "₹99",
    specs: {
      Type: "Basmati Rice",
      Weight: "5 kg",
      Brand: "Golden Harvest",
      Variety: "Long Grain",
      Packaging: "Plastic Bag",
    },
  },
  {
    category: "groceeey",
    id: "2",
    model: "Wheat Flour",
    image:
      "https://media.istockphoto.com/id/480241244/photo/bowl-filled-with-wheat-flour.webp?b=1&s=170667a&w=0&k=20&c=6e2VQtpOH6hlaIzWvAn9XsVuJqmigg38XsTgt_EHxDE=",
    price: "₹49",
    specs: {
      Type: "Whole Wheat",
      Weight: "2 kg",
      Brand: "Nature's Best",
      Packaging: "Paper Bag",
    },
  },
  {
    category: "groceeey",
    id: "3",
    model: "Cooking Oil",
    image:
      "https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?cs=srgb&dl=pexels-pixabay-33783.jpg&fm=jpg",
    price: "₹149",
    specs: {
      Type: "Sunflower Oil",
      Volume: "1 liter",
      Brand: "Healthy Choice",
      Packaging: "Plastic Bottle",
    },
  },
  {
    category: "groceeey",
    id: "4",
    model: "Milk",
    image:
      "https://png.pngtree.com/background/20230425/original/pngtree-almond-milk-in-bottle-and-milk-in-a-glass-picture-image_2477921.jpg",
    price: "₹29",
    specs: {
      Type: "Cow's Milk",
      Volume: "1 liter",
      Brand: "Fresh Farms",
      Packaging: "Tetra Pack",
    },
  },
  {
    category: "groceeey",
    id: "5",
    model: "Eggs",
    image:
      "https://img.freepik.com/free-photo/raw-chicken-eggs-egg-box-white-surface_114579-53521.jpg",
    price: "₹39",
    specs: {
      Type: "Chicken Eggs",
      Quantity: "12 eggs",
      Brand: "Farm Fresh",
      Packaging: "Carton",
    },
  },
  {
    category: "groceeey",
    id: "6",
    model: "Sugar",
    image:
      "https://t4.ftcdn.net/jpg/03/19/37/75/360_F_319377582_bE83iovSQCRB79zOL2OnV3cOP4jEA7Qb.jpg",
    price: "₹49",
    specs: {
      Type: "Granulated Sugar",
      Weight: "1 kg",
      Brand: "Sweet Delights",
      Packaging: "Plastic Bag",
    },
  },
  {
    category: "groceeey",
    id: "7",
    model: "Tea Leaves",
    image:
      "https://m.media-amazon.com/images/I/81JEU3zZ+fS._AC_UF1000,1000_QL80_.jpg",
    price: "₹69",
    specs: {
      Type: "Black Tea",
      Weight: "250 grams",
      Brand: "Royal Tea",
      Packaging: "Sealed Pouch",
    },
  },
  {
    category: "groceeey",
    id: "8",
    model: "Canned Tomatoes",
    image:
      "https://m.media-amazon.com/images/I/71bhUzqkeRL._AC_UF1000,1000_QL80_.jpg",
    price: "₹29",
    specs: {
      Type: "Whole Peeled Tomatoes",
      Quantity: "400 grams",
      Brand: "Farm Fresh",
      Packaging: "Can",
    },
  },
  {
    category: "groceeey",
    id: "9",
    model: "Pasta",
    image: "https://m.media-amazon.com/images/I/71ImcOHDXSL.jpg",
    price: "₹39",
    specs: {
      Type: "Spaghetti",
      Weight: "500 grams",
      Brand: "Golden Wheat",
      Packaging: "Packet",
    },
  },
  {
    category: "groceeey",
    id: "10",
    model: "Green Beans",
    image:
      "https://media.istockphoto.com/id/184329392/photo/close-up-of-a-bunch-of-green-beans.webp?b=1&s=170667a&w=0&k=20&c=3TuhlOYqm4aZJMb-7AN9WStKg7MGEA-pWoY7lxpKMMQ=",
    price: "₹49",
    specs: {
      Type: "Fresh Green Beans",
      Weight: "500 grams",
      Brand: "Organic Harvest",
      Packaging: "Plastic Bag",
    },
  },
  {
    category: "groceeey",
    id: "11",
    model: "Cereal",
    image:
      "https://miro.medium.com/v2/resize:fit:1080/1*7THyMkhh6hwf5OiEp9uOvw.jpeg",
    price: "₹79",
    specs: {
      Type: "Honey Oat Cereal",
      Weight: "400 grams",
      Brand: "NutriCrunch",
      Packaging: "Box",
    },
  },
  {
    category: "groceeey",
    id: "12",
    model: "Peanut Butter",
    image:
      "https://www.simpleskincare.com/sk-eu/content/dam/brands/kissan/india/2152286-8901030810978.png",
    price: "₹99",
    specs: {
      Type: "Smooth Peanut Butter",
      Weight: "500 grams",
      Brand: "Nuts 'n More",
      Packaging: "Jar",
    },
  },
  {
    category: "groceeey",
    id: "13",
    model: "Cereal",
    image:
      "https://c1.wallpaperflare.com/preview/286/961/265/muesli-bowl-healthy-food.jpg",
    price: "₹79",
    specs: {
      Type: "Honey Oat Cereal",
      Weight: "400 grams",
      Brand: "NutriCrunch",
      Packaging: "Box",
    },
  },
  {
    category: "groceeey",
    id: "14",
    model: "Canned Tuna",
    image:
      "https://c8.alamy.com/comp/H0712K/tuna-can-tin-of-flake-chunk-tuna-H0712K.jpg",
    price: "₹49",
    specs: {
      Type: "Chunk Light Tuna",
      Quantity: "185 grams",
      Brand: "Ocean Catch",
      Packaging: "Can",
    },
  },
  {
    category: "groceeey",
    id: "15",
    model: "Potato Chips",
    image:
      "https://www.vp-packaging.com/wp-content/uploads/2019/08/potato-chips-packaging-with-VMPET-film-inside.jpg",
    price: "₹39",
    specs: {
      Type: "Classic Salted",
      Weight: "150 grams",
      Brand: "SnackMaster",
      Packaging: "Packet",
    },
  },
  {
    category: "groceeey",
    id: "16",
    model: "Orange Juice",
    image:
      "https://img.freepik.com/free-vector/carton-box-with-orange-juice-surrounded-by-citruses-leaves_1268-15516.jpg?size=626&ext=jpg&ga=GA1.1.1826414947.1698969600&semt=ais",
    price: "₹79",
    specs: {
      Type: "100% Pure Orange Juice",
      Volume: "1 liter",
      Brand: "Fresh Squeeze",
      Packaging: "Carton",
    },
  },
  {
    category: "groceeey",
    id: "17",
    model: "Canned Soup",
    image:
      "https://m.media-amazon.com/images/I/71x6FKidgCL._AC_UF894,1000_QL80_.jpg",
    price: "₹49",
    specs: {
      Type: "Tomato Soup",
      Quantity: "400 grams",
      Brand: "Homemade Taste",
      Packaging: "Can",
    },
  },
  {
    category: "groceeey",
    id: "18",
    model: "Chocolate Bar",
    image:
      "https://www.yourboxsolution.com/blog/wp-content/uploads/2020/06/chocolate-bar-packaging-header.jpg",
    price: "₹29",
    specs: {
      Type: "Milk Chocolate",
      Weight: "100 grams",
      Brand: "Sweet Temptations",
      Packaging: "Wrapper",
    },
  },
  {
    category: "groceeey",
    id: "19",
    model: "Breakfast Cereal",
    image:
      "https://images-cdn.ubuy.co.in/634e6dfba95ed46ce64df672-kelloggs-breakfast-cereal-variety-pack.jpg",
    price: "₹69",
    specs: {
      Type: "Corn Flakes",
      Weight: "500 grams",
      Brand: "Crispy Mornings",
      Packaging: "Box",
    },
  },
  {
    category: "groceeey",
    id: "20",
    model: "Pasta Sauce",
    image:
      "https://www.tradeindia.com/_next/image/?url=https%3A%2F%2Ftiimg.tistatic.com%2Ffp%2F1%2F007%2F511%2Fspicy-and-tasty-chemical-free-knorr-pizza-pasta-sauce-for-eating-200g-pack--189.jpg&w=750&q=75",
    price: "₹59",
    specs: {
      Type: "Tomato Basil Sauce",
      Volume: "350 grams",
      Brand: "Italian Delights",
      Packaging: "Jar",
    },
  },
  {
    category: "groceeey",
    id: "21",
    type: "Acer",
    model: "Acer Aspire 5",
    image:
      "https://static-ecapac.acer.com/media/catalog/product/a/5/a515-58m_nx.khfsi.001.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=500&width=500&canvas=500:500",
    price: "₹44,999",
    specs: {
      RAM: "8 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Expandable via SD Card",
      display: "15.6-inch Full HD LED Display",
      processor: "Intel Core i5",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10",
      battery: "Up to 8 hours",
    },
  },
  {
    category: "laptop",
    id: "22",
    type: "dell",
    model: "Dell XPS 13",
    image:
      "https://www.cnet.com/a/img/resize/7e94135ecd41c33f4839173a40cc9049f346db15/hub/2018/03/06/e5a2feca-b999-4255-a631-a59641023af0/fl-dellxps13-cnet-still.jpg?auto=webp&fit=cover&height=482&width=856",
    price: "₹89,999",
    specs: {
      RAM: "16 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.4-inch 4K Ultra HD InfinityEdge Display",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "23",
    type: "dell",
    model: "Dell XPS 13",
    image: "https://m.media-amazon.com/images/I/61OBvwVHtQL.jpg",
    price: "₹89,999",
    specs: {
      RAM: "16 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.4-inch 4K Ultra HD InfinityEdge Display",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "24",
    type: "dell",
    model: "Dell XPS 13",
    image:
      "https://mysterio.yahoo.com/api/res/1.2/yZMQFGxjHAZWMB7ARIHtzA--/ZHByPTI7dz04NzU7YXBwaWQ9ZW5nYWRnZXQ-/https://s.yimg.com/os/creatr-uploaded-images/2022-07/8a806231-0e9c-11ed-b472-b338ac49ac62.cf.webp",
    price: "₹89,999",
    specs: {
      RAM: "16 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.4-inch 4K Ultra HD InfinityEdge Display",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "25",
    type: "hp",
    model: "HP Spectre x360",
    image:
      "https://www.shutterstock.com/image-photo/jakarta-indonesia-february-5-2019-260nw-1304548852.jpg",
    price: "₹79,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.3-inch 4K OLED Touchscreen",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 10 hours",
    },
  },
  {
    category: "laptop",
    id: "26",
    type: "lenovo",
    model: "Lenovo ThinkPad X1 Carbon",
    image: "https://m.media-amazon.com/images/I/51FOmWwmqaL.jpg",
    price: "₹89,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch Full HD IPS Display",
      processor: "Intel Core i7",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10 Pro",
      battery: "Up to 15 hours",
    },
  },
  {
    category: "laptop",
    id: "27",
    type: "Asus",
    model: "ASUS ROG Zephyrus G14",
    image:
      "https://onsitego.com/blog/wp-content/uploads/2020/09/ASUS-ROG-Zephyrus-G14-Review.jpg",
    price: "₹1,29,999",
    specs: {
      RAM: "32 GB",
      ROM: "1 TB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch WQXGA IPS Display",
      processor: "AMD Ryzen 9",
      graphics: "NVIDIA GeForce RTX 3060",
      operatingSystem: "Windows 10",
      battery: "Up to 10 hours",
    },
  },
  {
    category: "laptop",
    id: "28",
    type: "Applelaptop",
    model: "Apple MacBook Air",
    image:
      "https://c4.wallpaperflare.com/wallpaper/48/248/995/apple-macbook-laptop-shadow-wallpaper-preview.jpg",
    price: "₹92,990",
    specs: {
      RAM: "8 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.3-inch Retina Display",
      processor: "Apple M1",
      graphics: "Apple M1 GPU",
      operatingSystem: "macOS Big Sur",
      battery: "Up to 18 hours",
    },
  },
  {
    category: "laptop",
    id: "29",
    type: "Microsoftlaptop",
    model: "Microsoft Surface Laptop 4",
    image: "https://i.ytimg.com/vi/Z2MyXuHstIs/maxresdefault.jpg",
    price: "₹94,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.5-inch PixelSense Touchscreen",
      processor: "Intel Core i5",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 10",
      battery: "Up to 11 hours",
    },
  },
  {
    category: "laptop",
    id: "30",
    model: "LG Gram 17",
    image:
      "https://i.gadgets360cdn.com/large/Asus_Oled_laptops_launch_1630653088391.jpg",
    price: "₹1,19,999",
    specs: {
      RAM: "16 GB",
      ROM: "1 TB SSD",
      expandableMemory: "Not Expandable",
      display: "17-inch WQXGA IPS Display",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
    },
  },
  {
    category: "laptop",
    id: "31",
    type: "charger",
    model: "Dell Laptop Charger",
    image:
      "https://m.media-amazon.com/images/I/51GvWC7uAtL._AC_UF1000,1000_QL80_.jpg",
    price: "₹999",
    specs: {
      "Input Voltage": "100-240V AC",
      "Output Voltage": "19.5V DC",
      "Output Current": "3.34A",
      "Connector Size": "7.4mm x 5.0mm",
      Compatibility: "Dell Inspiron, XPS, Latitude",
    },
  },
  {
    category: "laptop",
    id: "32",
    type: "hp",
    model: "HP Laptop Battery",
    image:
      "https://m.media-amazon.com/images/I/61ddDVB6qwL._AC_UF1000,1000_QL80_.jpg",
    price: "₹1,499",
    specs: {
      Capacity: "5200mAh",
      Voltage: "10.8V",
      "Battery Type": "Li-ion",
      Compatibility: "HP ProBook, EliteBook",
    },
  },
  {
    category: "laptop",
    id: "33",
    type: "lenovo",
    model: "Lenovo ThinkPad L14",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2022/6/QO/PU/XJ/105622681/lenovo-thinkpad-l14-gen-1-2-.jpg",
    price: "₹59,999",
    specs: {
      RAM: "8 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch Full HD Display",
      processor: "Intel Core i5",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10 Pro",
      battery: "Up to 10 hours",
    },
  },
  {
    category: "laptop",
    id: "34",
    type: "Asus",
    model: "ASUS VivoBook 15",
    image:
      "https://rukminim2.flixcart.com/image/850/1000/jz05rww0/computer/s/5/t/asus-na-laptop-original-imafgrzrfwynmzeg.jpeg?q=90",
    price: "₹44,999",
    specs: {
      RAM: "8 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD Display",
      processor: "AMD Ryzen 5",
      graphics: "AMD Radeon Vega 8",
      operatingSystem: "Windows 10",
      battery: "Up to 7 hours",
    },
  },
  {
    category: "laptop",
    id: "35",
    type: "Microsoftlaptop",
    model: "Microsoft Surface Book 3",
    image: "https://i.gadgets360cdn.com/large/image_1_1582035622506.png",
    price: "₹1,49,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.5-inch PixelSense Touchscreen",
      processor: "Intel Core i7",
      graphics: "NVIDIA GeForce GTX 1650",
      operatingSystem: "Windows 10",
      battery: "Up to 15 hours",
    },
  },
  {
    category: "laptop",
    id: "36",
    type: "hp",
    model: "HP Envy x360",
    image:
      "https://static1.xdaimages.com/wordpress/wp-content/uploads/2022/11/HP-Envy-x360-13-10-16.jpg",
    price: "₹74,999",
    specs: {
      RAM: "16 GB",
      ROM: "1 TB SSD",
      expandableMemory: "Not Expandable",
      display: "13.3-inch 4K OLED Touchscreen",
      processor: "AMD Ryzen 7",
      graphics: "AMD Radeon Vega",
      operatingSystem: "Windows 10",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "37",
    type: "Acer",
    model: "Acer Predator Helios 300",
    image:
      "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1688578763/Croma%20Assets/Computers%20Peripherals/Laptop/Images/272085_0_liscin.png?tr=w-360",
    price: "₹1,09,999",
    specs: {
      RAM: "32 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD 144Hz Display",
      processor: "Intel Core i7",
      graphics: "NVIDIA GeForce RTX 3060",
      operatingSystem: "Windows 10",
      battery: "Up to 6 hours",
    },
  },
  {
    category: "laptop",
    id: "38",
    type: "Applelaptop",
    model: "Apple MacBook Pro",
    image:
      "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1685969095/Croma%20Assets/Computers%20Peripherals/Laptop/Images/256605_li76nl.png?tr=w-360",
    price: "₹1,19,990",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "13.3-inch Retina Display",
      processor: "Apple M1",
      graphics: "Apple M1 GPU",
      operatingSystem: "macOS Big Sur",
      battery: "Up to 17 hours",
    },
  },
  {
    category: "laptop",
    id: "39",
    type: "Asus",
    model: "ASUS ROG Strix G15",
    image: "https://m.media-amazon.com/images/I/81fZmxBbQgL.jpg",
    price: "₹1,19,999",
    specs: {
      RAM: "16 GB",
      ROM: "1 TB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD 240Hz Display",
      processor: "AMD Ryzen 9",
      graphics: "NVIDIA GeForce RTX 3070",
      operatingSystem: "Windows 10",
      battery: "Up to 5 hours",
    },
  },
  {
    category: "laptop",
    id: "40",
    type: "Asus",
    model: "ASUS ZenBook 14",
    image:
      "https://dlcdnwebimgs.asus.com/gain/1adf89fe-897b-4ed8-a491-c56091513407/",
    price: "₹89,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch Full HD",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 10 hours",
    },
  },

  {
    category: "laptop",
    id: "41",
    type: "Asus",
    model: "ASUS VivoBook 15",
    image:
      "https://dlcdnwebimgs.asus.com/gain/f5d267ef-9fde-4244-80cc-7413cec40944/",
    price: "₹54,999",
    specs: {
      RAM: "8 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD",
      processor: "Intel Core i5",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10",
      battery: "Up to 8 hours",
    },
  },

  {
    category: "laptop",
    id: "42",
    type: "Asus",
    model: "ASUS TUF Gaming A15",
    image:
      "https://images.hindustantimes.com/tech/img/2020/06/10/1600x900/20200528_003630_1591756296188_1591756305393.jpg",
    price: "₹79,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD 144Hz Display",
      processor: "AMD Ryzen 7",
      graphics: "NVIDIA GeForce GTX 1660 Ti",
      operatingSystem: "Windows 10",
      battery: "Up to 6 hours",
    },
  },

  {
    category: "laptop",
    id: "43",
    type: "Asus",
    model: "ASUS Chromebook Flip C434",
    image:
      "https://edgeup.asus.com/wp-content/uploads/2019/12/c4343-696x464.jpg",
    price: "₹49,999",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB eMMC",
      expandableMemory: "MicroSD Card Slot",
      display: "14-inch Full HD Touchscreen",
      processor: "Intel Core m3",
      graphics: "Intel HD Graphics 615",
      operatingSystem: "Chrome OS",
      battery: "Up to 10 hours",
    },
  },

  {
    category: "laptop",
    id: "44",
    type: "Asus",
    model: "ASUS ROG Zephyrus G14",
    image: "https://rog.asus.com/media/1578096205427.webp",
    price: "₹1,29,999",
    specs: {
      RAM: "32 GB",
      ROM: "1 TB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch QHD 120Hz Display",
      processor: "AMD Ryzen 9",
      graphics: "NVIDIA GeForce RTX 3060",
      operatingSystem: "Windows 10",
      battery: "Up to 8 hours",
    },
  },

  {
    category: "laptop",
    id: "45",
    type: "lenovo",
    model: "Lenovo Ideapad S340",
    image: "https://m.media-amazon.com/images/I/61Am9MNg3oL.jpg",
    price: "₹49,999",
    specs: {
      RAM: "12 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD",
      processor: "Intel Core i7",
      graphics: "NVIDIA GeForce MX250",
      operatingSystem: "Windows 10",
      battery: "Up to 8 hours",
    },
  },

  {
    category: "laptop",
    id: "46",
    type: "lenovo",
    model: "Lenovo ThinkPad X1 Carbon",
    image: "https://m.media-amazon.com/images/I/71wJJL7q8nL.jpg",
    price: "₹1,29,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch 4K OLED Touchscreen",
      processor: "Intel Core i7",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "47",
    type: "lenovo",
    model: "Lenovo Yoga C740",
    image:
      "https://m.media-amazon.com/images/I/61bDvi8s8RL._AC_UF1000,1000_QL80_.jpg",
    price: "₹69,999",
    specs: {
      RAM: "8 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch Full HD Touchscreen",
      processor: "Intel Core i5",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10",
      battery: "Up to 10 hours",
    },
  },

  {
    category: "laptop",
    id: "48",
    type: "lenovo",
    model: "Lenovo Legion 5",
    image: "https://m.media-amazon.com/images/I/61ItfhQmaFL.jpg",
    price: "₹79,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD 144Hz Display",
      processor: "AMD Ryzen 7",
      graphics: "NVIDIA GeForce GTX 1660 Ti",
      operatingSystem: "Windows 10",
      battery: "Up to 6 hours",
    },
  },

  {
    category: "laptop",
    id: "49",
    type: "lenovo",
    model: "Lenovo Chromebook Duet",
    image:
      "https://m.media-amazon.com/images/I/71TkmfAZTpL._AC_UF1000,1000_QL80_.jpg",
    price: "₹29,999",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB eMMC",
      expandableMemory: "MicroSD Card Slot",
      display: "10.1-inch Full HD Touchscreen",
      processor: "MediaTek Helio P60T",
      graphics: "Mali-G72 MP3",
      operatingSystem: "Chrome OS",
      battery: "Up to 10 hours",
    },
  },

  {
    category: "laptop",
    id: "50",
    type: "hp",
    model: "HP Envy x360",
    image: "https://m.media-amazon.com/images/I/61t+LjBGkXL.jpg",
    price: " ₹84,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch Full HD Touchscreen",
      processor: "Intel Core i5",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "51",
    type: "hp",
    model: "HP Pavilion 15",
    image:
      "https://m.media-amazon.com/images/I/71r5gZx4u0L._AC_UF1000,1000_QL80_.jpg",
    price: "₹59,999",
    specs: {
      RAM: "8 GB",
      ROM: "256 GB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch Full HD",
      processor: "Intel Core i3",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10",
      battery: "Up to 8 hours",
    },
  },
  {
    category: "laptop",
    id: "52",
    type: "hp",
    model: "HP Omen 15",
    image: "https://m.media-amazon.com/images/I/81AAyd-Eb+L.jpg",
    price: "₹99,999",
    specs: {
      RAM: "32 GB",
      ROM: "1 TB SSD",
      expandableMemory: "Not Expandable",
      display: "15.6-inch 4K OLED",
      processor: "Intel Core i9",
      graphics: "NVIDIA GeForce RTX 3080",
      operatingSystem: "Windows 11",
      battery: "Up to 6 hours",
    },
  },
  {
    category: "laptop",
    id: "53",
    type: "hp",
    model: "HP Chromebook 14",
    image: "https://m.media-amazon.com/images/I/81l0Biby4cL.jpg",
    price: "₹34,999",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB eMMC",
      expandableMemory: "Not Expandable",
      display: "14-inch HD",
      processor: "Intel Celeron",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Chrome OS",
      battery: "Up to 10 hours",
    },
  },
  {
    category: "laptop",
    id: "54",
    type: "hp",
    model: "HP Stream 11",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2022/3/CV/MC/TS/45907665/81wyojox4gl-ac-sl1500-1--500x500.jpg",
    price: "₹24,999",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB eMMC",
      expandableMemory: "MicroSD Card Slot",
      display: "11.6-inch HD",
      processor: "Intel Celeron",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10",
      battery: "Up to 8 hours",
    },
  },
  {
    category: "laptop",
    id: "55",
    type: "hp",
    model: "HP EliteBook 840",
    image: "https://m.media-amazon.com/images/I/6112m6IOqaL.jpg",
    price: " ₹79,999",
    specs: {
      RAM: "16 GB",
      ROM: "512 GB SSD",
      expandableMemory: "Not Expandable",
      display: "14-inch Full HD Touchscreen",
      processor: "Intel Core i7",
      graphics: "Intel UHD Graphics",
      operatingSystem: "Windows 10 Pro",
      battery: "Up to 12 hours",
    },
  },
  {
    category: "laptop",
    id: "56",
    type: "iphone",
    model: "Apple iPhone 13",
    image:
      "https://www.apple.com/newsroom/images/product/iphone/standard/Apple_iPhone-13-Pro_iPhone-13-Pro-Max_09142021_inline.jpg.slideshow-xlarge.jpg",
    price: "₹79,900",
    specs: {
      RAM: "6 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "15.49 cm (6.1 inch) Super Retina XDR Display",
      camera: {
        rear: "12MP + 12MP",
        front: "12MP",
      },
      battery: "2815mAh Li-ion Battery",
      processor: "Apple A15 Bionic",
    },
  },
  {
    category: "laptop",
    id: "57",
    type: "iphone",
    model: "Apple iPhone 13 Pro",
    image: "https://doc.iwant.cz/pic/E0UY000501-600-600.jpg",
    price: "₹1,19,900",
    specs: {
      RAM: "6 GB",
      ROM: "256 GB",
      expandableMemory: "Not Expandable",
      display: "15.49 cm (6.1 inch) Super Retina XDR Display",
      camera: {
        rear: "12MP + 12MP + 12MP + 12MP",
        front: "12MP",
      },
      battery: "3095mAh Li-ion Battery",
      processor: "Apple A15 Bionic",
    },
  },
  {
    category: "mobile",
    id: "58",
    type: "iphone",
    model: "Apple iPhone 13 Mini",
    price: "₹69,900",
    image:
      "https://cdn.dxomark.com/wp-content/uploads/drafts/post-97844/Apple-iphone-13-mini-featured-image-packshot-review-Recovered-Recovered.jpg",
    specs: {
      RAM: "4 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "13.72 cm (5.4 inch) Super Retina XDR Display",
      camera: {
        rear: "12MP + 12MP",
        front: "12MP",
      },
      battery: "2438mAh Li-ion Battery",
      processor: "Apple A15 Bionic",
    },
  },
  {
    category: "mobile",
    id: "59",
    model: "Apple iPhone 12",
    type: "iphone",
    image:
      "https://img.giznext.com/assets/model/2/96/apple-iphone-12-bf42db0fa85b24eae7f527a7b5a260.jpg",
    price: "₹69,900",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB",
      expandableMemory: "Not Expandable",
      display: "15.49 cm (6.1 inch) Super Retina XDR Display",
      camera: {
        rear: "12MP + 12MP",
        front: "12MP",
      },
      battery: "2815mAh Li-ion Battery",
      processor: "Apple A14 Bionic",
    },
  },
  {
    category: "mobile",
    id: "60",
    type: "iphone",
    model: "Apple iPhone 12 Pro Max",
    image:
      "https://photos5.appleinsider.com/gallery/38960-74452-iPhone-12-Pro-Max-on-Table-with-Accessories-at-an-Angle-l.jpg",
    price: "₹1,29,900",
    specs: {
      RAM: "6 GB",
      ROM: "256 GB",
      expandableMemory: "Not Expandable",
      display: "16.95 cm (6.7 inch) Super Retina XDR Display",
      camera: {
        rear: "12MP + 12MP + 12MP + 12MP",
        front: "12MP",
      },
      battery: "3687mAh Li-ion Battery",
      processor: "Apple A14 Bionic",
    },
  },
  {
    category: "mobile",
    id: "61",
    model: "Apple iPhone SE",
    type: "iphone",
    price: "₹29,900",
    image:
      "https://www.91-img.com/gallery_images_uploads/a/4/a4cd5ffe4c9a8bd71731aee7b5541f6ec071653f.jpg?tr=h-630,c-at_max,q-80",
    specs: {
      RAM: "3 GB",
      ROM: "64 GB",
      expandableMemory: "Not Expandable",
      display: "11.94 cm (4.7 inch) Retina HD Display",
      camera: {
        rear: "12MP",
        front: "7MP",
      },
      battery: "1821mAh Li-ion Battery",
      processor: "Apple A13 Bionic",
    },
  },
  {
    category: "mobile",
    id: "62",
    model: "Apple iPhone 11",
    type: "iphone",
    price: "₹54,900",
    image: "https://cdn.mos.cms.futurecdn.net/cMoTNtvMD8wdTYp7Wd56V8.jpg",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB",
      expandableMemory: "Not Expandable",
      display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
      camera: {
        rear: "12MP + 12MP",
        front: "12MP",
      },
      battery: "3110mAh Li-ion Battery",
      processor: "Apple A13 Bionic",
    },
  },
  {
    category: "mobile",
    id: "63",
    model: "Apple iPhone XR",
    type: "iphone",
    price: "₹47,900",
    image:
      "https://www.apple.com/newsroom/images/product/iphone/standard/iPhone_XR_red-back_09122018_carousel.jpg.large.jpg",
    specs: {
      RAM: "3 GB",
      ROM: "64 GB",
      expandableMemory: "Not Expandable",
      display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
      camera: {
        rear: "12MP",
        front: "7MP",
      },
      battery: "2942mAh Li-ion Battery",
      processor: "Apple A12 Bionic",
    },
  },
  {
    category: "mobile",
    id: "64",
    model: "Apple iPhone X",
    type: "iphone",
    price: "₹89,000",
    image:
      "https://cellbuddy.in/buddy/wp-content/uploads/2022/09/X-Space-grey-2.png",
    specs: {
      RAM: "3 GB",
      ROM: "64 GB",
      expandableMemory: "Not Expandable",
      display: "14.73 cm (5.8 inch) Super Retina HD Display",
      camera: {
        rear: "12MP + 12MP",
        front: "7MP",
      },
      battery: "2716mAh Li-ion Battery",
      processor: "Apple A11 Bionic",
    },
  },
  {
    category: "mobile",
    id: "65",
    model: "Apple iPhone 8",
    type: "iphone",
    price: "₹39,900",
    image:
      "https://www.apple.com/newsroom/images/product/iphone/standard/iPhone8Plus_color_selection_inline.jpg.large.jpg",
    specs: {
      RAM: "2 GB",
      ROM: "64 GB",
      expandableMemory: "Not Expandable",
      display: "11.94 cm (4.7 inch) Retina HD Display",
      camera: {
        rear: "12MP",
        front: "7MP",
      },
      battery: "1821mAh Li-ion Battery",
      processor: "Apple A11 Bionic",
    },
  },
  {
    category: "mobile",
    id: "67",
    type: "vivo",
    model: "Vivo Y16",
    price: "₹11,990",
    image:
      "https://in-exstatic-vivofs.vivo.com/gdHFRinHEMrj3yPG/product/1671430862596/zip/img/webp/in-section1-kv-mb.jpg.webp",
    specs: {
      RAM: "6 GB",
      ROM: "128 GB",
      expandableMemory: "Expandable up to 512 GB",
      display: "16.94 cm (6.67 inch) Full HD+ Display",
      camera: {
        rear: "64MP + 8MP + 5MP + 2MP",
        front: "32MP",
      },
      battery: "5020mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 720G",
    },
  },
  {
    category: "mobile",
    id: "68",
    type: "vivo",
    model: "Vivo V21",
    price: "₹24,990",
    image:
      "https://fdn.gsmarena.com/imgroot/news/21/04/vivo-v21-5g-india-launch-date/-640x500m/gsmarena_004.jpg",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Expandable up to 256 GB",
      display: "16.36 cm (6.44 inch) AMOLED Display",
      camera: {
        rear: "64MP + 8MP + 2MP",
        front: "44MP + 64MP",
      },
      battery: "4000mAh Lithium Polymer Battery",
      processor: "MediaTek Dimensity 800U",
    },
  },
  {
    category: "mobile",
    id: "69",
    type: "vivo",
    model: "Vivo Y20",
    price: "₹13,990",
    image:
      "https://techatpark.in/wp-content/uploads/2021/01/VIVO-Y20-464-MOP-12735-OP-12535.jpeg",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB",
      expandableMemory: "Expandable up to 256 GB",
      display: "16.54 cm (6.51 inch) HD+ Display",
      camera: {
        rear: "13MP + 2MP + 2MP",
        front: "8MP",
      },
      battery: "5000mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 460",
    },
  },
  {
    category: "mobile",
    id: "70",
    type: "vivo",
    model: "Vivo X60 Pro",
    price: "₹49,990",
    image:
      "https://www.mobilityindia.com/wp-content/uploads/2021/04/vivo-X60-Pro.png",
    specs: {
      RAM: "12 GB",
      ROM: "256 GB",
      expandableMemory: "Not Expandable",
      display: "16.66 cm (6.56 inch) AMOLED Display",
      camera: {
        rear: "48MP + 13MP + 13MP",
        front: "32MP",
      },
      battery: "4200mAh Lithium Polymer Battery",
      processor: "Exynos 1080",
    },
  },
  {
    category: "mobile",
    id: "71",
    type: "vivo",
    model: "Vivo S1 Pro",
    price: "₹19,990",
    image:
      "https://www.giztop.com/media/catalog/product/cache/dc206057cdd42d7e34b9d36e347785ca/v/i/vivo_x50_pro_5g_1.png",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "16.21 cm (6.38 inch) Super AMOLED Display",
      camera: {
        rear: "48MP + 8MP + 2MP + 2MP",
        front: "32MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 665",
    },
  },
  {
    category: "mobile",
    id: "72",
    type: "vivo",
    model: "Vivo X50 Pro+",
    price: "₹49,990",
    image:
      "https://www.giztop.com/media/catalog/product/cache/dc206057cdd42d7e34b9d36e347785ca/v/i/vivo_x50_pro_5g_1.png",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "16.66 cm (6.56 inch) AMOLED Display",
      camera: {
        rear: "50MP + 13MP + 32MP + 13MP",
        front: "32MP",
      },
      battery: "4350mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 865",
    },
  },
  {
    category: "mobile",
    id: "73",
    type: "oneplus",
    model: "OnePlus 9",
    price: "₹49,999",
    image:
      "https://www.gizbot.com/images/2021-04/oneplus-9-pro-review_16179572824.jpg",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "16.66 cm (6.55 inch) Fluid AMOLED Display",
      camera: {
        rear: "48MP + 50MP + 2MP",
        front: "16MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 888",
    },
  },
  {
    category: "mobile",
    id: "74",
    type: "oneplus",
    model: "OnePlus Nord 2",
    price: "₹29,999",
    image:
      "https://www.ytechb.com/wp-content/uploads/2021/07/OnePlus-Nord-2-Wallpapers.webp",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "16.36 cm (6.43 inch) Fluid AMOLED Display",
      camera: {
        rear: "50MP + 8MP + 2MP",
        front: "32MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "MediaTek Dimensity 1200",
    },
  },
  {
    category: "mobile",
    id: "75",
    type: "oneplus",
    model: "OnePlus 8T",
    price: "₹42,999",
    image:
      "https://oasis.opstatics.com/content/dam/oasis/default/product-specs/8t-green.png",
    specs: {
      RAM: "12 GB",
      ROM: "256 GB",
      expandableMemory: "Not Expandable",
      display: "16.63 cm (6.55 inch) Fluid AMOLED Display",
      camera: {
        rear: "48MP + 16MP + 5MP + 2MP",
        front: "16MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 865",
    },
  },
  {
    category: "mobile",
    id: "76",
    type: "oneplus",
    model: "OnePlus 8 Pro",
    price: "₹54,999",
    image:
      "https://cdn.dxomark.com/wp-content/uploads/medias/post-47840/oneplus8Pro.jpg",
    specs: {
      RAM: "12 GB",
      ROM: "256 GB",
      expandableMemory: "Not Expandable",
      display: "17.22 cm (6.78 inch) Fluid AMOLED Display",
      camera: {
        rear: "48MP + 8MP + 48MP + 5MP",
        front: "16MP",
      },
      battery: "4510mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 865",
    },
  },
  {
    category: "mobile",
    id: "77",
    type: "oneplus",
    model: "OnePlus 7T",
    price: "₹37,999",
    image:
      "https://www.digitaltrends.com/wp-content/uploads/2019/09/oneplus-7t-back.jpg?p=1",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "16.63 cm (6.55 inch) Fluid AMOLED Display",
      camera: {
        rear: "48MP + 12MP + 16MP",
        front: "16MP",
      },
      battery: "3800mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 855+",
    },
  },
  {
    category: "mobile",
    id: "78",
    type: "oneplus",
    model: "OnePlus 7 Pro",
    price: "₹44,999",
    image:
      "https://www.androidauthority.com/wp-content/uploads/2019/05/OnePlus-7-Pro-phone-angled-on-table-back.jpg",
    specs: {
      RAM: "12 GB",
      ROM: "256 GB",
      expandableMemory: "Not Expandable",
      display: "16.94 cm (6.67 inch) Fluid AMOLED Display",
      camera: {
        rear: "48MP + 8MP + 16MP",
        front: "16MP",
      },
      battery: "4000mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 855",
    },
  },
  {
    category: "mobile",
    id: "79",
    model: "OnePlus 6T",
    type: "oneplus",
    price: "₹37,999",
    image:
      "https://www.reliancedigital.in/wp-content/uploads/2018/12/oneplus6T-design-1-1.jpg",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "16.28 cm (6.41 inch) Optic AMOLED Display",
      camera: {
        rear: "16MP + 20MP",
        front: "16MP",
      },
      battery: "3700mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 845",
    },
  },
  {
    category: "mobile",
    id: "80",
    type: "oneplus",
    model: "OnePlus 5T",
    price: "₹32,999",
    image:
      "https://cdn.opstatics.com/store/20170907/assets/images/support/support-list/model-specs-list/details/5t-white.png",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "15.26 cm (6.01 inch) Optic AMOLED Display",
      camera: {
        rear: "16MP + 20MP",
        front: "16MP",
      },
      battery: "3300mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 835",
    },
  },
  {
    category: "mobile",
    id: "81",
    type: "samsung",
    model: "Samsung Galaxy S21",
    price: "₹69,999",
    image:
      "https://fdn.gsmarena.com/imgroot/news/21/02/galaxy-s21-deal/-1220x526/gsmarena_001.jpg",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Not Expandable",
      display: "15.84 cm (6.2 inch) Dynamic AMOLED 2X Display",
      camera: {
        rear: "12MP + 12MP + 64MP",
        front: "10MP",
      },
      battery: "4000mAh Lithium Polymer Battery",
      processor: "Exynos 2100",
    },
  },
  {
    category: "mobile",
    id: "82",
    type: "samsung",
    model: "Samsung Galaxy Note 20 Ultra",
    price: "₹1,04,999",
    image:
      "https://cdn.dxomark.com/wp-content/uploads/medias/post-62683/samsung-galaxy-note20-ultra-5g-1-1.jpg",
    specs: {
      RAM: "12 GB",
      ROM: "256 GB",
      expandableMemory: "Expandable up to 1 TB",
      display: "17.53 cm (6.9 inch) Dynamic AMOLED 2X Display",
      camera: {
        rear: "108MP + 12MP + 12MP",
        front: "10MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "Exynos 990",
    },
  },
  {
    category: "mobile",
    id: "83",
    type: "samsung",
    model: "Samsung Galaxy Note 20 Ultra",
    price: "₹1,04,999",
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-note20-ultra-3.jpg",
    specs: {
      RAM: "12 GB",
      ROM: "256 GB",
      expandableMemory: "Expandable up to 1 TB",
      display: "17.53 cm (6.9 inch) Dynamic AMOLED 2X Display",
      camera: {
        rear: "108MP + 12MP + 12MP",
        front: "10MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "Exynos 990",
    },
  },
  {
    category: "mobile",
    id: "84",
    type: "samsung",
    model: "Samsung Galaxy A52",
    price: "₹23,999",
    image:
      "https://fdn.gsmarena.com/imgroot/reviews/21/samsung-galaxy-a52/lifestyle/-1024w2/gsmarena_001.jpg",
    specs: {
      RAM: "6 GB",
      ROM: "128 GB",
      expandableMemory: "Expandable up to 1 TB",
      display: "16.40 cm (6.5 inch) Super AMOLED Display",
      camera: {
        rear: "64MP + 12MP + 5MP + 5MP",
        front: "32MP",
      },
      battery: "4500mAh Lithium Polymer Battery",
      processor: "Qualcomm Snapdragon 720G",
    },
  },
  {
    category: "mobile",
    id: "85",
    type: "samsung",
    model: "Samsung Galaxy M32",
    price: "₹14,999",
    image:
      "https://www.91-cdn.com/hub/wp-content/uploads/2021/06/samsung-galaxy-m32-image-feat.jpg",
    specs: {
      RAM: "4 GB",
      ROM: "64 GB",
      expandableMemory: "Expandable up to 1 TB",
      display: "16.26 cm (6.4 inch) Super AMOLED Display",
      camera: {
        rear: "64MP + 8MP + 2MP + 2MP",
        front: "20MP",
      },
      battery: "6000mAh Lithium Polymer Battery",
      processor: "MediaTek Helio G80",
    },
  },
  {
    category: "mobile",
    id: "86",
    type: "samsung",
    model: "Samsung Galaxy S10",
    price: "₹53,999",
    image:
      "https://www.gizbot.com/images/2019-02/samsung-galaxy-s10-plus_155107488940.jpg",
    specs: {
      RAM: "8 GB",
      ROM: "128 GB",
      expandableMemory: "Expandable up to 512 GB",
      display: "15.49 cm (6.1 inch) Dynamic AMOLED Display",
      camera: {
        rear: "12MP + 12MP + 16MP",
        front: "10MP",
      },
      battery: "3400mAh Lithium Polymer Battery",
      processor: "Exynos 9820",
    },
  },
  {
    category: "clothes",
    id: "87",
    model: "Men's Casual T-Shirt",
    price: "₹499",
    image: "https://images.meesho.com/images/products/280866197/gahde_512.webp",
    specs: {
      Material: "Cotton",
      Size: "M",
      Color: "Navy Blue",
      Style: "Short Sleeve",
      Pattern: "Striped",
    },
  },
  {
    category: "clothes",
    id: "88",
    model: "Women's Floral Maxi Dress",
    price: "₹899",
    image:
      "https://www.alamodelabel.in/cdn/shop/products/image_b61b3060-940c-4b2a-85b6-9349f9f7c9bf_600x.jpg?v=1622811875",
    specs: {
      Material: "Polyester",
      Size: "L",
      Color: "Red",
      Style: "Sleeveless",
      Pattern: "Floral",
    },
  },
  {
    category: "clothes",
    id: "89",
    model: "Men's Slim Fit Jeans",
    price: "₹799",
    image:
      "https://indoshop.in/wp-content/uploads/2019/09/men-slim-fit-jeans-500x500.jpg",
    specs: {
      Material: "Denim",
      Size: "32",
      Color: "Black",
      Style: "Straight Leg",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "90",
    model: "Women's Workout Leggings",
    price: "₹599",
    image: "https://images.meesho.com/images/products/214348898/ijtgp_512.webp",
    specs: {
      Material: "Spandex",
      Size: "S",
      Color: "Gray",
      Style: "High Waist",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "91",
    model: "Men's Formal Shirt",
    price: "₹899",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2020/10/XC/DL/SO/92086267/men-formal-shirts.jpg",
    specs: {
      Material: "Cotton",
      Size: "L",
      Color: "White",
      Style: "Long Sleeve",
      Pattern: "Checked",
    },
  },
  {
    category: "clothes",
    id: "92",
    model: "Women's Summer Dress",
    price: "₹649",
    image:
      "https://image.made-in-china.com/2f0j00PydTJbrzLlqv/Women-Summer-Fashion-Elastic-Beach-Dress-Floral-Painted-Causal-Dress-Women-s-Suit-2-Pieces-Dresses-Set.webp",
    specs: {
      Material: "Cotton",
      Size: "M",
      Color: "Yellow",
      Style: "Short Sleeve",
      Pattern: "Printed",
    },
  },
  {
    category: "clothes",
    id: "93",
    model: "Men's Cargo Shorts",
    price: "₹549",
    image:
      "https://sslimages.shoppersstop.com/sys-master/images/hd5/h62/14748022636574/206874103_9113_alt1.jpg_2000Wx3000H",
    specs: {
      Material: "Cotton",
      Size: "XL",
      Color: "Khaki",
      Style: "Knee-Length",
      Pattern: "Camouflage",
    },
  },
  {
    category: "clothes",
    id: "94",
    model: "Women's Sweater",
    price: "₹799",
    image: "https://m.media-amazon.com/images/I/81nvDjL+xjL._AC_UY1100_.jpg",
    specs: {
      Material: "Wool",
      Size: "S",
      Color: "Blue",
      Style: "Round Neck",
      Pattern: "Striped",
    },
  },
  {
    category: "clothes",
    id: "95",
    model: "Men's Hooded Jacket",
    price: "₹1,199",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2020/10/XM/CO/AZ/115391760/cotton-double-bed-sheets-500x500.jpg",
    specs: {
      Material: "Polyester",
      Size: "L",
      Color: "Black",
      Style: "Full Zip",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "96",
    model: "Women's Denim Skirt",
    price: "₹699",
    image:
      "https://assets.ajio.com/medias/sys_master/root/20230320/2vEN/6418c020aeb26924e3d1c192/-473Wx593H-469311903-iceblue-MODEL.jpg",
    specs: {
      Material: "Denim",
      Size: "M",
      Color: "Indigo",
      Style: "A-Line",
      Pattern: "Distressed",
    },
  },
  {
    category: "clothes",
    id: "97",
    model: "Men's Chino Pants",
    price: "₹799",
    image:
      "https://5.imimg.com/data5/LT/MD/YE/SELLER-13012241/mens-chinos-trousers-500x500.jpg",
    specs: {
      Material: "Cotton",
      Size: "32",
      Color: "Khaki",
      Style: "Slim Fit",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "98",
    model: "Women's Cardigan Sweater",
    price: "₹699",
    image: "https://images.meesho.com/images/products/57943293/bz4h2_512.webp",
    specs: {
      Material: "Acrylic",
      Size: "M",
      Color: "Beige",
      Style: "Open Front",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "99",
    model: "Men's Sports T-Shirt",
    price: "₹499",
    image:
      "https://bodymark.in/cdn/shop/products/SP7410-NGREEN_S_1.jpg?v=1674545597",
    specs: {
      Material: "Polyester",
      Size: "XL",
      Color: "Black",
      Style: "Short Sleeve",
      Pattern: "Mesh",
    },
  },
  {
    category: "clothes",
    id: "100",
    model: "Women's Pencil Skirt",
    price: "₹599",
    image:
      "https://i.pinimg.com/originals/78/f9/12/78f912641d5b304dcb1f4b5e5db2d6a1.jpg",
    specs: {
      Material: "Cotton",
      Size: "S",
      Color: "Navy Blue",
      Style: "High Waist",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "101",
    model: "Men's Plaid Flannel Shirt",
    price: "₹699",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2023/2/OF/PI/DD/185260820/flannel-shirt-500x500.jpg",
    specs: {
      Material: "Flannel",
      Size: "L",
      Color: "Red/Black",
      Style: "Long Sleeve",
      Pattern: "Plaid",
    },
  },
  {
    category: "clothes",
    id: "102",
    model: "Women's Jumpsuit",
    price: "₹899",
    image:
      "https://imagescdn.planetfashion.in/img/app/product/7/792236-9283686.jpg?auto=format&w=494.40000000000003",
    specs: {
      Material: "Polyester",
      Size: "M",
      Color: "Green",
      Style: "Sleeveless",
      Pattern: "Printed",
    },
  },
  {
    category: "clothes",
    id: "103",
    model: "Men's Cargo Pants",
    price: "₹749",
    image:
      "https://assets.ajio.com/medias/sys_master/root/20230621/JiNv/64927b49d55b7d0c638e9439/-473Wx593H-463983577-grey-MODEL.jpg",
    specs: {
      Material: "Cotton",
      Size: "34",
      Color: "Olive Green",
      Style: "Straight Leg",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "104",
    model: "Women's Hooded Sweatshirt",
    image:
      "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/5829332/2018/8/6/01777914-6a34-4c08-88a0-533f38402ffb1533555262903-Roadster-Women-Burgundy-Solid-Hooded-Sweatshirt-621533555261-1.jpg",
    price: "₹799",
    specs: {
      Material: "Cotton",
      Size: "L",
      Color: "Gray",
      Style: "Hooded",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "105",
    model: "Men's Denim Jacket",
    price: "₹1,099",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2021/1/ZR/EA/AO/122363882/mens-denim-jacket.jpg",
    specs: {
      Material: "Denim",
      Size: "XL",
      Color: "Blue",
      Style: "Button-Up",
      Pattern: "Distressed",
    },
  },
  {
    category: "clothes",
    id: "106",
    model: "Women's Wrap Dress",
    price: "₹699",
    image:
      "https://assets.ajio.com/medias/sys_master/root/20230419/uEwV/643fc48f711cf97ba7354bf4/-473Wx593H-441923217-green-MODEL.jpg",
    specs: {
      Material: "Polyester",
      Size: "M",
      Color: "Red",
      Style: "V-Neck",
      Pattern: "Floral",
    },
  },
  {
    category: "clothes",
    id: "107",
    model: "Boys' Graphic T-Shirt",
    price: "₹349",
    image:
      "https://assets.ajio.com/medias/sys_master/root/20230623/KBuq/6494ca16d55b7d0c63a5b244/-473Wx593H-464447987-white-MODEL.jpg",
    specs: {
      Material: "Cotton",
      Size: "4-5 Years",
      Color: "Blue",
      Style: "Short Sleeve",
      Pattern: "Printed",
    },
  },
  {
    category: "clothes",
    id: "108",
    model: "Girls' Floral Dress",
    image:
      "https://www.fayonkids.com/cdn/shop/products/fayon-kids-yellow-floral-printed-dress-for-girls-36897391870208.jpg?v=1650348557",
    price: "₹499",
    specs: {
      Material: "Polyester",
      Size: "3-4 Years",
      Color: "Pink",
      Style: "Sleeveless",
      Pattern: "Floral",
    },
  },
  {
    category: "clothes",
    id: "109",
    model: "Boys' Denim Shorts",
    price: "₹399",
    image:
      "https://kiddopanti.com/cdn/shop/files/AW23BJS047-LtWash-a_1600x.jpg?v=1698321401",
    specs: {
      Material: "Denim",
      Size: "6-7 Years",
      Color: "Light Blue",
      Style: "Knee-Length",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "110",
    model: "Girls' Leggings",
    price: "₹299",
    image: "https://m.media-amazon.com/images/I/61DrGuULkFL._AC_UY1100_.jpg",
    image: "",
    specs: {
      Material: "Spandex",
      Size: "2-3 Years",
      Color: "Purple",
      Style: "Full Length",
      Pattern: "Striped",
    },
  },
  {
    category: "clothes",
    id: "111",
    model: "Boys' Hooded Sweatshirt",
    price: "₹449",
    image:
      "https://images.bestsellerclothing.in/data/JJ/16-june-2022/291257601_g3.jpg?width=1080&height=1355&mode=fill&fill=blur&format=auto",
    specs: {
      Material: "Cotton",
      Size: "8-9 Years",
      Color: "Gray",
      Style: "Hooded",
      Pattern: "Solid",
    },
  },
  {
    category: "clothes",
    id: "112",
    model: "Boys' Denim Shorts",
    price: "₹399",
    image: "https://images.meesho.com/images/products/270087478/tsjlh_512.jpg",
    specs: {
      Material: "Denim",
      Size: "6-7 Years",
      Color: "Light Blue",
      Style: "Knee-Length",
      Pattern: "Solid",
    },
  },
  {
    category: "footwear",
    id: "113",
    model: "Running Shoes",
    image:
      "https://images.unsplash.com/photo-1610969524113-bae462bb3892?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cnVubmluZyUyMHNob2VzfGVufDB8fDB8fHww",
    price: "₹1,799",
    specs: {
      Brand: "New Balance",
      Model: "Fresh Foam Arishi V3",
      Size: "US 9",
      Color: "Grey/Red",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "114",
    model: "Casual Shoes",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2021/1/KS/WX/SM/8852934/mens-high-fashion-casual-shoes.JPG",
    price: "₹1,199",
    specs: {
      Brand: "Vans",
      Model: "Classic Slip-On",
      Size: "US 10",
      Color: "Checkerboard",
      "Closure Type": "Slip-on",
    },
  },
  {
    category: "footwear",
    id: "115",
    model: "Sports Sandals",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBhrQErpNZgxmsqdiSrl7KIoxzXcdk3GSsIQ&usqp=CAU",
    price: "₹899",
    specs: {
      Brand: "Reebok",
      Model: "Classic Sliders",
      Size: "US 8",
      Color: "Navy/White",
      "Closure Type": "Slip-on",
    },
  },
  {
    category: "footwear",
    id: "116",
    model: "Slippers",
    image:
      "https://cdn.pixabay.com/photo/2017/06/17/16/16/amazing-2412614_640.jpg",
    price: "₹349",
    specs: {
      Brand: "Crocs",
      Model: "Classic Clogs",
      Size: "US 7/8",
      Color: "Black",
      "Closure Type": "Slip-on",
    },
  },
  {
    category: "footwear",
    id: "117",
    model: "Hiking Boots",
    image:
      "https://img.freepik.com/premium-photo/hiking-boots-close-up-tourist-walking-trail-italy_522472-7360.jpg",
    price: "₹2,299",
    specs: {
      Brand: "Salomon",
      Model: "X Ultra 3 Mid GTX",
      Size: "US 10",
      Color: "Black",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "118",
    model: "Running Shoes",
    image:
      "https://images.unsplash.com/photo-1610969770059-7084269fa3be?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cnVubmluZyUyMHNob2VzfGVufDB8fDB8fHww",
    price: "₹2,199",
    specs: {
      Brand: "Saucony",
      Model: "Guide 13",
      Size: "US 9",
      Color: "Blue/Black",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "119",
    model: "Casual Shoes",
    image: "https://images.meesho.com/images/products/115311286/vu1pu_512.webp",
    price: "₹1,399",
    specs: {
      Brand: "Converse",
      Model: "Chuck Taylor All Star",
      Size: "US 10",
      Color: "White",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "110",
    model: "Sports Sandals",
    image: "https://images.meesho.com/images/products/8158606/e32b1_512.webp",
    price: "₹799",
    specs: {
      Brand: "Nike",
      Model: "Sunray Protect 2",
      Size: "US 8",
      Color: "Black/Volt",
      "Closure Type": "Velcro",
    },
  },
  {
    category: "footwear",
    id: "112",
    model: "Hiking Boots",
    image:
      "https://s3.amazonaws.com/images.gearjunkie.com/uploads/2021/03/WaterproofHikingBootsforWomen-1.jpeg",
    price: "₹2,799",
    specs: {
      Brand: "Merrell",
      Model: "Moab 2 Mid WP",
      Size: "US 10",
      Color: "Earth",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "216",
    model: "uxury Italian Leather ShoesL",
    image:
      "https://rukminim2.flixcart.com/image/1200/1200/km0x5zk0/shoe/z/u/h/10-sfl-12314-burgandy-10-san-frissco-burgundy-original-imagfykshxyc4yvu.jpeg?q=70",
    price: "₹19,999",
    specs: {
      Brand: "Gucci",
      Model: "Ace GG Supreme",
      Size: "US 9",
      Color: "Beige/Ebony",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "217",
    model: "Designer High-Top Sneakers",
    image: "https://cdn.mos.cms.futurecdn.net/sFRhaBuhttQRQoP5PFptEZ.jpg",
    price: "₹22,999",
    specs: {
      Brand: "Balenciaga",
      Model: "Triple S",
      Size: "US 10",
      Color: "White",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "218",
    model: "Handmade Italian Leather Boots",
    image:
      "https://tuccidilusso.com/cdn/shop/articles/Buy_Tucci_di_lusso_Mens_handmade_Luxury_Italian_leather_handcrafted_mens_custom_made_designers_shoes2_345x345@2x.jpg?v=1637335031",
    price: "₹26,999",
    specs: {
      Brand: "Berluti",
      Model: "Alessandro Venezia",
      Size: "US 10",
      Color: "Brown",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "219",
    model: "Luxury Patent Leather Loafers",
    image:
      "https://rukminim1.flixcart.com/image/850/850/xif0q/shoe/v/c/g/6-1414-sign-app-black-original-imaggtmp3qz5gspu.jpeg?q=20",
    price: "₹15,999",
    specs: {
      Brand: "Tom Ford",
      Model: "Wessex",
      Size: "US 9",
      Color: "Black",
      "Closure Type": "Slip-on",
    },
  },
  {
    category: "footwear",
    id: "220",
    model: "Signature Red Bottom Pumps",
    image:
      "https://cdn.magzter.com/1598631389/1673425344/articles/SyrJAPWeX1677508678786/HAUTE-HEEL.jpg",
    price: "₹29,999",
    specs: {
      Brand: "Christian Louboutin",
      Model: "So Kate",
      Size: "US 8",
      Color: "Nude",
      "Closure Type": "Slip-on",
    },
  },
  {
    category: "footwear",
    id: "221",
    model: "Handcrafted Leather Oxfords",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2021/6/UX/QM/HQ/23643672/img-6696-500x500.JPG",
    price: "₹20,999",
    specs: {
      Brand: "John Lobb",
      Model: "William",
      Size: "US 9",
      Color: "Dark Brown",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "222",
    model: "Exotic Crocodile Skin Boots",
    image:
      "https://cdna.lystit.com/520/650/n/photos/dellamoda/e325d83f/mezlan-BROWN-Rx4855f-Shoes-Sport-Exotic-Crocodile-Suede-Leather-Rugged-Boots-mzs3552.jpeg",
    price: "₹36,999",
    specs: {
      Brand: "Louis Vuitton",
      Model: "Ultimate Boots",
      Size: "US 10",
      Color: "Black",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "223",
    model: "Luxury Velvet Slippers",
    image:
      "https://image.made-in-china.com/202f0j00KhbgCZvzEocR/Autumn-and-Winter-Ladies-Light-Luxury-Velvet-Floor-Soft-Bottom-Warm-Cotton-Slippers.webp",
    price: "₹14,999",
    specs: {
      Brand: "Dolce & Gabbana",
      Model: "Velvet Devotion",
      Size: "US 8",
      Color: "Navy",
      "Closure Type": "Slip-on",
    },
  },
  {
    category: "footwear",
    id: "224",
    model: "Bespoke Hand-Painted Shoes",
    image:
      "https://i.pinimg.com/474x/f5/c7/30/f5c730106e27fa7d3fe5a394cc3ca1df.jpg",
    price: "₹49,999",
    specs: {
      Brand: "Edward Green",
      Model: "Chiswick",
      Size: "US 9",
      Color: "Hand-Painted",
      "Closure Type": "Lace-up",
    },
  },
  {
    category: "footwear",
    id: "225",
    model: "Swarovski Crystal Studded Heels",
    image:
      "https://i.etsystatic.com/8379098/r/il/36a044/3675057111/il_570xN.3675057111_fdck.jpg",
    price: "₹39,999",
    specs: {
      Brand: "Jimmy Choo",
      Model: "LANCE",
      Size: "US 8",
      Color: "Champagne",
      "Closure Type": "Buckle",
    },
  },
];
module.exports = {
  global,
};
